### ISSUE TITLE
Error claiming with Coinbase Smart Wallet 

### ISSUE THREAD

**Issue by 0x4d4n** [thirdweb-example/account-abstraction#1]
When attempting to claim or perform any transaction in this demo using the Coinbase Smart Wallet you receive the error:
Error: eth_sendUserOperation error: {"message":"UserOperation reverted during simulation with reason: AA23 reverted: ECDSA: invalid signature length","code":-32500}
Status: 200
Code: UNKNOWN

To reproduce sign in and select Coinbase, use and existing or create a new Coinbase Smart Wallet. Attempt to Claim via Sponsored Transactions.

**Comment by joaquim-verges** [comment]
@0x4d4n try it in our playground https://playground.thirdweb.com 

in general though, using coinbase smart wallet as an admin of another smart account is not generally recommended. If you're looking for sponsored transactions using cb smart wallet, check out this post: https://blog.thirdweb.com/changelog/easy-coinbase-smart-wallet-integration-with-eip-5792-hooks/
